In [66]:
import numpy as np
import pandas as pd
data = pd.read_excel(r'/home/bek/Documents/ОАВР/Official_Foreign_Exchange_Rates_NBRK_on_13_04_2020.xls')
ts = pd.DataFrame(data, columns=['USD']) # time series
ts = ts.values
ts = ts.reshape(-1)
time_series = ts

In [2]:
l = len(time_series) // 2
ts = time_series[l:]
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
scores = np.empty(14)
for k in range(2, 16):
    X = time_series[:l - l%k]
    X = X.reshape(l//k, k)
    KMean = KMeans(n_clusters=k)
    KMean.fit(X)
    y_true = KMean.labels_
    X1 = ts[:l - l%k]
    X1 = X1.reshape(l//k, k)
    y_pred = KMean.predict(X1)
    scores[k - 2] = accuracy_score(y_true, y_pred)
k = 2 + np.argmax(scores)
print(max(scores),k)

0.392 2


In [67]:
tau = 10
l = len(time_series) - tau + 1
X = np.empty(shape=(tau, l))
for i in range(tau):
    for j in range(l):
        X[i][j] = time_series[i + j]
print(X)

[[371.56 371.56 371.56 ... 448.52 447.6  443.5 ]
 [371.56 371.56 371.56 ... 447.6  443.5  443.5 ]
 [371.56 371.56 371.14 ... 443.5  443.5  443.5 ]
 ...
 [370.49 370.49 370.49 ... 435.54 432.55 431.03]
 [370.49 370.49 369.35 ... 432.55 431.03 431.03]
 [370.49 369.35 370.55 ... 431.03 431.03 431.03]]


In [68]:

C = X@X.transpose() / l
print(C)

[[147813.62601955 147871.73812179 147929.55158228 147983.00369878
  148033.77629043 148083.24672118 148129.38031955 148174.76814094
  148219.65771813 148264.55499328]
 [147871.73812179 147933.04641955 147991.15852179 148044.91635092
  148096.73356925 148146.32458289 148192.59482098 148238.73273544
  148283.73461874 148328.62419593]
 [147929.55158228 147991.15852179 148052.46681955 148106.52329043
  148158.64622138 148209.28186171 148255.67268269 148301.94723686
  148347.69921324 148392.70109654]
 [147983.00369878 148044.91635092 148106.52329043 148163.81701609
  148216.25514053 148267.21167352 148314.67446354 148361.08350041
  148406.9721165  148452.72409287]
 [148033.77629043 148096.73356925 148158.64622138 148216.25514053
  148271.93719206 148323.21503788 148371.00974277 148418.49635193
  148464.51945071 148510.4080668 ]
 [148083.24672118 148146.32458289 148209.28186171 148267.21167352
  148323.21503788 148377.74206375 148425.86875479 148473.6908609
  148520.79196823 148566.81506701]

In [69]:
L, V = np.linalg.eigh(C)
print(L, end='\n\n')
print(V)

[5.19454006e-01 6.66979634e-01 1.01358761e+00 1.31993321e+00
 1.45206523e+00 1.80917903e+00 2.83888395e+00 7.67448347e+00
 6.29630621e+01 1.48303669e+06]

[[ 0.08396242 -0.19791182 -0.33797674 -0.12118167  0.08059853  0.37049436
  -0.39396526 -0.45875975  0.46451899  0.31568772]
 [-0.21695383  0.46259341  0.48124629 -0.10892252 -0.25041425 -0.34847959
  -0.04607691 -0.23733402  0.39132803  0.31582084]
 [ 0.29517282 -0.43442457  0.13966683  0.27303605  0.39252997 -0.37996365
   0.37804846  0.0223322   0.29731332  0.31595263]
 [-0.38026214  0.24458324 -0.36075904  0.42787765 -0.13598086  0.30263696
   0.42120326  0.24422523  0.18791546  0.3160745 ]
 [ 0.45676574 -0.0755501  -0.09156312 -0.47906135 -0.49379616  0.05246778
   0.16041668  0.41350089  0.0670276   0.31619132]
 [-0.45828304 -0.07090398  0.09567456 -0.45805669  0.51358584  0.05326815
  -0.14984188  0.41629127 -0.05977033  0.31630416]
 [ 0.38469009  0.24130231  0.35344447  0.4325482   0.12150124  0.31027126
  -0.41593482  0.2533

In [70]:
r = 8
L_ = L[2:]
V_ = V[2:]
print(L_, end='\n\n')
print(V_)

[1.01358761e+00 1.31993321e+00 1.45206523e+00 1.80917903e+00
 2.83888395e+00 7.67448347e+00 6.29630621e+01 1.48303669e+06]

[[ 0.29517282 -0.43442457  0.13966683  0.27303605  0.39252997 -0.37996365
   0.37804846  0.0223322   0.29731332  0.31595263]
 [-0.38026214  0.24458324 -0.36075904  0.42787765 -0.13598086  0.30263696
   0.42120326  0.24422523  0.18791546  0.3160745 ]
 [ 0.45676574 -0.0755501  -0.09156312 -0.47906135 -0.49379616  0.05246778
   0.16041668  0.41350089  0.0670276   0.31619132]
 [-0.45828304 -0.07090398  0.09567456 -0.45805669  0.51358584  0.05326815
  -0.14984188  0.41629127 -0.05977033  0.31630416]
 [ 0.38469009  0.24130231  0.35344447  0.4325482   0.12150124  0.31027126
  -0.41593482  0.25332391 -0.18288165  0.31640877]
 [-0.30123444 -0.43142777 -0.13271146  0.25463062 -0.40714494 -0.3738521
  -0.38257056  0.03507937 -0.29559419  0.31651176]
 [ 0.22218606  0.45409249 -0.48196881 -0.10103633  0.25395475 -0.35647073
   0.03680948 -0.23014817 -0.39471523  0.31661248]
 [

In [78]:
V_a = np.empty(shape=(tau-1,r)) # a - asterisk
for i in range(tau-1):
    for j in range(r):
        V_a[i][j] = V[i][j]
print(V_a.shape)
print(V_a)

(9, 8)
[[ 0.08396242 -0.19791182 -0.33797674 -0.12118167  0.08059853  0.37049436
  -0.39396526 -0.45875975]
 [-0.21695383  0.46259341  0.48124629 -0.10892252 -0.25041425 -0.34847959
  -0.04607691 -0.23733402]
 [ 0.29517282 -0.43442457  0.13966683  0.27303605  0.39252997 -0.37996365
   0.37804846  0.0223322 ]
 [-0.38026214  0.24458324 -0.36075904  0.42787765 -0.13598086  0.30263696
   0.42120326  0.24422523]
 [ 0.45676574 -0.0755501  -0.09156312 -0.47906135 -0.49379616  0.05246778
   0.16041668  0.41350089]
 [-0.45828304 -0.07090398  0.09567456 -0.45805669  0.51358584  0.05326815
  -0.14984188  0.41629127]
 [ 0.38469009  0.24130231  0.35344447  0.4325482   0.12150124  0.31027126
  -0.41593482  0.25332391]
 [-0.30123444 -0.43142777 -0.13271146  0.25463062 -0.40714494 -0.3738521
  -0.38257056  0.03507937]
 [ 0.22218606  0.45409249 -0.48196881 -0.10103633  0.25395475 -0.35647073
   0.03680948 -0.23014817]]


In [79]:
Q = np.array(time_series[l:])
print(len(Q))

9


In [83]:
P = np.linalg.lstsq(V_a, Q)
P = P[0]
print(P)

[ 113.9170152   256.223831   -444.14813453  158.17363085   98.05277748
 -491.22928035 -519.40889359  604.30194792]


/home/bek/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [88]:
V_t = V_[:r].transpose()
print(V_t.shape)
print(V_t)

(10, 8)
[[ 0.29517282 -0.38026214  0.45676574 -0.45828304  0.38469009 -0.30123444
   0.22218606 -0.08603187]
 [-0.43442457  0.24458324 -0.0755501  -0.07090398  0.24130231 -0.43142777
   0.45409249 -0.19235559]
 [ 0.13966683 -0.36075904 -0.09156312  0.09567456  0.35344447 -0.13271146
  -0.48196881  0.33489273]
 [ 0.27303605  0.42787765 -0.47906135 -0.45805669  0.4325482   0.25463062
  -0.10103633 -0.11985059]
 [ 0.39252997 -0.13598086 -0.49379616  0.51358584  0.12150124 -0.40714494
   0.25395475 -0.07482239]
 [-0.37996365  0.30263696  0.05246778  0.05326815  0.31027126 -0.3738521
  -0.35647073  0.36964714]
 [ 0.37804846  0.42120326  0.16041668 -0.14984188 -0.41593482 -0.38257056
   0.03680948  0.39170452]
 [ 0.0223322   0.24422523  0.41350089  0.41629127  0.25332391  0.03507937
  -0.23014817 -0.4587093 ]
 [ 0.29731332  0.18791546  0.0670276  -0.05977033 -0.18288165 -0.29559419
  -0.39471523 -0.47190055]
 [ 0.31595263  0.3160745   0.31619132  0.31630416  0.31640877  0.31651176
   0.31661

In [100]:
# answer
x = np.linalg.inv( (1 - V_t@V_t.transpose()) )@(V_t@V_a.transpose()@Q) )
print(x, end='\n\n')
print(x[0])

[ 428.5  -180.75  424.    -96.   -224.   -416.     32.     80.     32.
  192.  ]
